#!/usr/bin/env bash
# Bash script that makes localhost resolve to 127.0.0.2 
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed -i -e '1i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
